### ISSUE TITLE
invalid packet: sequence number mismatch(48 != 1(expected))

### ISSUE THREAD

**Issue by AlejandroJL** [tmtm/ruby-mysql#21]
Hello! im using 2.9.11
The Query is : DB.query("UPDATE tasks SET status=1 WHERE taskid={taskID}")
Ideas?

Thanks and greats

**Comment by xionglingfeng** [comment]
I still hit this bug at FreeBSD. I tried from version 2.9.3 to 2.9.14, all of them have the same problem

    :err=>#<Mysql::ProtocolError: invalid packet: sequence number mismatch(107 != 4(expected))>

But in Mac OS X, version 2.9.14 works perfectly. Maybe it is platform-dependent?
