### ISSUE TITLE
$con = Mysql.connect('hostname', 'username', 'password', 'dbname')

### ISSUE THREAD

**Issue by lujeii** [tmtm/ruby-mysql#31]
protocol.rb:655:in `parse': invalid packet: scramble_length(0) != length of scramble(21) (Mysql::ProtocolError)

ruby-mysql 2.11.0

**Comment by tmtm** [comment]
What version of mysqld are you using?

**Comment by lujeii** [comment]
ruby-mysql 2.11.0

**Comment by lujeii** [comment]
> What version of mysqld are you using?
ruby-mysql 2.11.0
mysql 5.1.73

**Comment by lujeii** [comment]
> What version of mysqld are you using?

My MySQL database has been upgraded to MySQL 5.7.25. Now Ruby MySQL 2.11.0 can work correctly.
thank you very much
