### ISSUE TITLE
Invalid packet: sequence number mismatch

### ISSUE THREAD

**Issue by markfrommer** [tmtm/ruby-mysql#8]
Sorry, I accidentally closed my issue.  I am getting this error sometimes, but not on every query. The error seems to occur when the result includes more data; shorter results are OK. I am using MySQL 5.5.8, ruby-mysql 2.9.4. OS-X 10.6.5. Error message follows:

Mysql::ProtocolError: invalid packet: sequence number mismatch(32 != 11(expected)): SELECT \* FROM templates WHERE (templates.site_id = 50)

**Comment by xionglingfeng** [comment]
I still hit this bug at FreeBSD. I tried from version 2.9.3 to 2.9.14, all of them have the same problem

    :err=>#<Mysql::ProtocolError: invalid packet: sequence number mismatch(107 != 4(expected))>

But in Mac OS X, version 2.9.14 works perfectly. Maybe it is platform-dependent?
